# Generated by Django 2.1.4 on 2019-01-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.DecimalField(decimal_places=6, editable=False, max_digits=9)),
                ('date', models.DateField(editable=False)),
            ],
        ),
    ]
