# Generated by Django 2.1.4 on 2019-01-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findpet', '0002_auto_20190105_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='pet_pics/None/no-img.jpg', upload_to='pet_pics/'),
        ),
    ]
